### ISSUE TITLE
bug: x13_refresh "Fixed" and "Current" ?

### ISSUE THREAD

**Issue by annasmyk** [palatej/rjd3x13#14]
x13_refresh "Fixed" and "Current"  don't seem to work 
(all other policy values give results,.. )
- "current" is supposed to be "current AO approach" (GUI) ?
-  fixed = fixed model (GUI) ?
just to make sure...

Example :
y_raw<-rjd3toolkit::ABS$X0.2.08.10.M
spec_x13_d<-rjd3x13::spec_x13("rsa5c")
sa_x13_d <- rjd3x13::x13(y_raw, spec_x13_d)
current_result_spec <- sa_x13_d$result_spec
current_domain_spec <- sa_x13_d$estimation_spec
spec_x13_ref <- x13_refresh(current_result_spec, # point spec to be refreshed
                              current_domain_spec, #domain spec (set of constraints)
                              policy = "Fixed")

RETURNS
Error in .jcall("jdplus/x13/base/r/X13", "Ljdplus/x13/base/api/x13/X13Spec;", :
java.lang.NullPointerException: Cannot invoke "jdplus.toolkit.base.api.data.Parameter.getValue()" because the return value of "jdplus.x13.base.api.regarima.MeanSpec.getCoefficient()" is null

**Comment by palatej** [comment]
Ok. Solved in 2.9.1 (changes in mean correction not integrated yet in R)
