### ISSUE TITLE
No estimation when benchmarking enabled 

### ISSUE THREAD

**Issue by annasmyk** [palatej/rjd3x13#17]
when customizing benchmarking part in the spec:
- spec written correctly 
- but no estimation 

example 
spec_x13_d<-rjd3x13::spec_x13("rsa5c")
spec_x13_d<-set_benchmarking(spec_x13_d,
                             enabled = TRUE,
                             target = "Normal",
                             rho = 0.8,
                             lambda = 0.5,
                             forecast = FALSE,
                             bias = "None")
y<-rjd3toolkit::ABS$X0.2.09.10.M
sa_x13_d<- rjd3x13::x13(y, spec_x13_d)

returns
Error in type$value(name = paste(prefix, code, sep = "_"))$number() :
attempt to apply non-function

**Comment by AQLT** [comment]
You only have this error with the option `target = "Normal"` (and also in tramoseats). It comes from rjd3toolkit. Can you try modifying rjd3toolkit replacing those lines:
https://github.com/palatej/rjd3toolkit/blob/d11dd73df422f0dbee872b0632f0a482aa8256e9/R/spec_benchmarking.R#L33-L35
By
```
if (!is.na(target)) {
    if (target == "NORMAL")
        target <- "ORIGINAL"
    x$target <- sprintf("TARGET_%s", target)
}
```
?
It should solve the issue.

**Comment by palatej** [comment]
I will change "Normal" by"Original" in the function parameters. It is more clear ("Normal" doesn't mean anything). Also to be noted that the default in the Java code is "CalendarAdjusted"
