### ISSUE TITLE
Structure of "outlier" item in JD3_REGARIMA_SPEC

### ISSUE THREAD

**Issue by TanguyBarthelemy** [palatej/rjd3x13#20]
The structure of the item `outlier` of `JD3_REGARIMA_SPEC` is diffrent from `JD3_TRAMO_SPEC`:

In object of class `JD3_REGARIMA_SPEC`, there is a nested list named `outlier` (also) which contains the type of automatically detected outliers with their va.

```
spec1 <- rjd3x13::spec_regarima("RG5C")
str(spec1$outlier)

List of 7
 $ outliers     :List of 3
  ..$ :List of 2
  .. ..$ type: chr "AO"
  .. ..$ va  : num 0
  ..$ :List of 2
  .. ..$ type: chr "LS"
  .. ..$ va  : num 0
  ..$ :List of 2
  .. ..$ type: chr "TC"
  .. ..$ va  : num 0
 $ span         :List of 5
  ..$ type: chr "ALL"
  ..$ d0  : NULL
  ..$ d1  : NULL
  ..$ n0  : int 0
  ..$ n1  : int 0
  ..- attr(*, "class")= chr "JD3_SPAN"
 $ defva        : num 0
 $ method       : chr "ADDONE"
 $ monthlytcrate: num 0.7
 $ maxiter      : int 30
 $ lsrun        : int 0
```

In object of class `JD3_TRAMO_SPEC`, there is no nested list `outlier` but the outliers type are directly *checked* through `TRUE `and `FALSE`
```
spec2 <- rjd3tramoseats::spec_tramo("trfull")
str(spec2$outlier)

List of 9
 $ enabled: logi TRUE
 $ span   :List of 5
  ..$ type: chr "ALL"
  ..$ d0  : NULL
  ..$ d1  : NULL
  ..$ n0  : int 0
  ..$ n1  : int 0
  ..- attr(*, "class")= chr "JD3_SPAN"
 $ ao     : logi TRUE
 $ ls     : logi TRUE
 $ tc     : logi TRUE
 $ so     : logi FALSE
 $ va     : num 0
 $ tcrate : num 0.7
 $ ml     : logi FALSE
```

Is it possible to modify the **regarima** specification to have the same pattern as the **tramo** specification?

**Comment by palatej** [comment]
In X13, you can specify different critical values for the different outlier types (not in Tramo). That option is seldom used and is not available through the graphical interface. However, It exists in the core libraries (FORTRAN and Java). That's why I prefer to maintain it in the R package.

**Comment by TanguyBarthelemy** [comment]
Ok then, how to specity different critical values for different outlier types (in X13) ?

This program returns an error :

```
spec_x13_d <- rjd3x13::spec_x13("rsa5c")

spec_x13_d <- rjd3toolkit::set_outlier(
    spec_x13_d,
    outliers.type = c("LS", "TC"),
    critical.value = c(5, 2))

> Error in if (missing(critical.value) | is.na(critical.value)) { : 
>   the condition has length > 1
```

- Should we change the condition `missing(critical.value) | is.na(critical.value)` at the beginning of `set_outlier.default` (to include length > 1 critical values) ?
- What if the meaning of `defva` ?
